### ISSUE TITLE
Using UITableViewController as content

### ISSUE THREAD

**Issue by rhanzies62** [Baseflow/Xamarin-Sidebar#21] opened 2015-03-06 13:56 UTC
When i use UITableViewController as my content, the scrolling functionality is not working.

**Comment by jdehlin** [comment] 2015-03-09 15:02
I was able to reproduce your problem by making the Content controller inherit from UITableViewController. I haven't been able to come up with a solution yet but I would guess it has something to do with the gesture recognizer for sliding the menu open. I will continue to try to find a solution for this bug. In the mean time you can work around this by following the tutorial linked below.

http://developer.xamarin.com/guides/ios/user_interface/tables/part_2_-_populating_a_table_with_data/

I apologize for the inconvenience.

**Comment by l3ender** [comment] 2015-10-02 09:35
This is due to the Pan event handler trapping the scroll event and not passing it on to the table view controller. See http://stackoverflow.com/questions/5426306/

I've forked and am planning to work on this.

**Comment by l3ender** [comment] 2015-11-20 00:58
I was able to circumvent this issue by wrapping my UITableViewController inside of a UINavigationController. I haven't had issues with it yet (though I'm in an early development phase). I think that's a suitable workaround given that there is typically an action generated from a table that merits navigation. If navigation isn't required, the navigation bar can be hidden.

**Comment by jasondenney** [comment] 2016-10-20 04:25
I saw this bug after I saw Swipe Gesture BUG #48 and in my app we do have a UITableViewController inside of a UITabViewController that is inside of a UINavigationController and do still see the issue.  I took a simple approach of just putting in a boolean to control if the gesture should be enabled and put it in a pull request Added DisablePanGesture #60 if this could be helpful for you as well.

**Comment by jdehlin** [comment] 2016-10-20 04:36
Closing as resolved by #60

**Closed as completed by jdehlin** 2016-10-20 04:36 UTC
